### PR TITLE
Fix 1.8.9 Compact

### PR DESCRIPTION
**Pull request by HowardZHY**

### CODE REVIEW

**Comment by bbayu123** [comment]
This just sounds like you changed your one and only fork to "1.8.9", then blame BK because no other spigot or fork server uses "1.8.9".

Like breaking a wall in your house/apartment, then requesting the floor plan to be changed, but the wall never had to be broken down in the first place.

For reference: 
1. https://hub.spigotmc.org/versions/ - "1.8.9" does not exist, because it's identical to 1.8.8.
2. https://papermc.io/legacy - Scroll to the bottom and you'll see 1.8.8, not 1.8.9. Again 1.8.9 does not exist because there are no changes to Spigot.

I personally find "Spigot (or insert fork name) 1.8.9" to be illegal, but it's up to berger's decision.

**Comment by HowardZHY** [comment]
I don't need to blame. This is just a small improvement that no one had thought it before and it's important for me.

**Comment by bergerkiller** [comment]
This PR is useless because you haven't even covered 5% of where 1.8.8 is declared as the final version for 1.8. Such as https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/templates/TemplateResolver.java#L24

Before people start doing dumb 1.8.10 version number "newness" wars, is there any particular reason why ButtitoSpigot uses 1.8.9? I'd prefer they dont do dumb stuff like this.

**Comment by bergerkiller** [comment]
But I might concess on doing !(>=1.9) instead of (<=1.8.8) in places, as it's at least cleaner.

**Comment by bbayu123** [comment]
> is there any particular reason why BurritoSpigot uses 1.8.9?

That's the wrong question to ask. You should ask "is there any particular reason why **your fork of burrito** uses 1.8.9". From what I know, burrito itself follows taco and nacho to use 1.8.8.

**Comment by bbayu123** [comment]
> But I might concess on doing !(>=1.9) instead of (<=1.8.8) in places, as it's at least cleaner.

I wouldn't. This dumb version number nonsense needs to be highly discouraged.

**Comment by HowardZHY** [comment]
I realized for plugin servers, 1.8.9 would be somewhat dumb. This is different from Forge.

**Pull request closed without merging**
